#install java
- name: Install some tool
  apt: 
    name: 
      - curl
      - apt-transport-https
    state: present 
    update_cache: yes
    force: yes
  become: yes

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Install Oracle Java 8
  become: yes
  apt: name=openjdk-8-jdk state=latest

- name: select java8
  become: yes
  shell: update-java-alternatives -s java-1.8.0-openjdk-amd64

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  become: yes

#install jenkins server

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present
  become: yes

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: true
  become: yes

- name: Install jenkins.
  apt:
    name: jenkins
    state: present
  become: yes
- name: start jenkins
  service: name=jenkins state=started enabled=yes
  become: yes

- name: insert jenkins rule
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8080
    action: insert
    jump: ACCEPT
    comment: Accept jenkins
  become: yes

#config jenkins
- name: Wait for Jenkins to start up before proceeding.
  command: >
    curl -D - --silent --max-time 5 http://127.0.0.1:8080/cli/
  args:
    warn: false
  register: result
  until: >
    (result.stdout.find("403 Forbidden") != -1)
    or (result.stdout.find("200 OK") != -1)
    and (result.stdout.find("Please wait while") == -1)
  retries: 5
  delay: 10
  changed_when: false
  check_mode: false

- name: install docker dependencies
  become: yes
  apt:
    name: "{{item}}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    -  software-properties-common
    
- name: add repo key  
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  become: yes
- name: add apt repository docker:
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  become: yes

- name: Installs docker
  yum: 
    name: docker-ce # docker in some distros
    state: installed     

- name: install docker
  become: yes
  apt:
    name: "{{item}}"
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: restart docker
  systemd: 
    name: docker 
    state: restarted
    daemon_reload: yes
    enabled: yes
